import { useMemo } from "react";
import { BarChart3, Clock3, Gauge, PackageCheck } from "lucide-react";
import { Line, LineChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import PageHeader from "../components/PageHeader";
import KpiCard from "../components/KpiCard";

export default function Performance({kpis}){
 const orders=kpis?.orders||[]; const machines=kpis?.machines||[]; const summary=kpis?.summary||{};
 const trend=useMemo(()=>orders.slice().sort((a,b)=>new Date(a.due_datetime)-new Date(b.due_datetime)).map((o,i)=>({period:String(i+1).padStart(2,"0"),tardiness:Number(o.tardiness_hours||0),ontime:o.on_time?1:0})),[orders]);
 const otd=orders.length?orders.filter(o=>o.on_time).length/orders.length*100:0; const util=machines.length?machines.reduce((a,m)=>a+Number(m.utilization_pct||0),0)/machines.length:0;
 return <><PageHeader title="Performance Analytics" description="Track service, machine efficiency, setup burden and inventory outcomes across planning runs."/><section className="kpi-grid kpi-grid-4"><KpiCard title="On-Time Delivery" value={`${otd.toFixed(1)}%`} subtitle="Current order result" icon={<PackageCheck size={19}/>} tone="green"/><KpiCard title="Average Delay" value={`${Number(summary.avg_tardiness_hours||0).toFixed(1)}h`} subtitle="Across all orders" icon={<Clock3 size={19}/>} tone="amber"/><KpiCard title="Utilization" value={`${util.toFixed(1)}%`} subtitle="Average machine utilization" icon={<Gauge size={19}/>} /><KpiCard title="Setup Time" value={`${(Number(summary.total_setup_min||0)/60).toFixed(1)}h`} subtitle="Sequence-dependent total" icon={<BarChart3 size={19}/>} /></section><div className="dashboard-grid"><div className="panel span-7"><div className="panel-header"><div><h2>Tardiness evolution</h2><p>Order-level tardiness sorted by due date in the current run.</p></div></div>{trend.length?<div className="chart-box"><ResponsiveContainer width="100%" height={360}><LineChart data={trend}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="period"/><YAxis/><Tooltip/><Line type="monotone" dataKey="tardiness" name="Tardiness (h)" stroke="#315A7D" strokeWidth={2.5} dot={false}/></LineChart></ResponsiveContainer></div>:<div className="empty-state">Run CP-SAT to populate performance history.</div>}</div><div className="panel span-5"><div className="panel-header"><div><h2>Management reading</h2><p>Use these metrics to demonstrate industrial impact.</p></div></div><div className="management-list"><div><strong>Customer</strong><span>On-Time Delivery, late orders, average delay</span></div><div><strong>Machine</strong><span>Utilization, occupancy, idle time, downtime</span></div><div><strong>Inventory</strong><span>Average stock, safety exposure, replenishment</span></div><div><strong>Optimization</strong><span>Objective, solve time, improvement vs baseline</span></div></div></div></div></>;
}
